### ISSUE TITLE
Newlines in Cookiecutter-generated project

### ISSUE THREAD

**Issue by ar-jan** [CentreForDigitalHumanities/cookiecutter-webapp-deluxe#23]
Projects generated with this template contain newlines at the location of `{% if ... %} ... {% endif %}` blocks, which breaks table rendering in case of markdown files (e.g. the "Development mode vs production mode" table). Looks like Jinja can ignore preceding/following whitespace using an extra dash like `{%- if %}`.

**Comment by jgonggrijp** [comment]
@ar-jan It appears that a part of your first sentence is missing. Could you edit the opening post to add the missing part?

**Comment by ar-jan** [comment]
@jgonggrijp not missing, but I clarified the sentence a bit.

**Comment by jgonggrijp** [comment]
Ah, I think my brains failed at parsing the sentence because I interpreted "containg" as "containing", rather than as the intended "contain". Thanks for clarifying!
