### ISSUE TITLE
Convert CI from Travis to Github Actions

### ISSUE THREAD

**Issue by ar-jan** [CentreForDigitalHumanities/cookiecutter-webapp-deluxe#25]
Changing to Github Actions should simplify things (fewer external services), and doesn't have a limit on free testing capacity.

**Comment by ar-jan** [comment]
It looks like the way to use postgres in an Action is via a [service container](https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers). This uses the [Docker postgres image](https://hub.docker.com/_/postgres).

I think this means we can't rely on peer authentication, and instead have to provide a TCP port-based connection string witih password. Thoughts?

**Comment by jgonggrijp** [comment]
I think you are right.

**Comment by ar-jan** [comment]
Done.
