### ISSUE TITLE
DeprecationWarning: Pattern `%d{DATE}` is deprecated

### ISSUE THREAD

**Issue by ar-jan** [CentreForDigitalHumanities/cookiecutter-webapp-deluxe#28]
Running tests:

> (node:1813) [log4js-node-DEP0004] DeprecationWarning: Pattern %d{DATE} is deprecated due to the confusion it causes when used. Please use %d{DATETIME} instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by ar-jan** [comment]
How should we use `--trace-deprecation` within an Angular project?

**Comment by jgonggrijp** [comment]
Suppose that you are running `ng <something>`. In theory, the following should work (you can generalize this):

    node --trace-deprecation `yarn bin`/ng <something>

**Comment by ar-jan** [comment]
Indeed, that works. `node --trace-deprecation $(yarn bin)/ng test --watch=false`.

Here the fix is to upgrade to [karma 6.3.12+](https://github.com/karma-runner/karma/releases/tag/v6.3.12).
