### ISSUE TITLE
Improve data-awareness in Angular

### ISSUE THREAD

**Issue by jgonggrijp** [CentreForDigitalHumanities/cookiecutter-webapp-deluxe#3]
We have democratically chosen Angular as the standard frontend framework for future projects. I'm concerned about Angular's lack of a counterpart to Backbone's models and collections, because of the following effects:

 - There is no separation of concerns between storing data and presenting data; components are responsible for both.
 - In the most common and most straightforward case, a component that represents data also stores those data, but since often multiple components present the same data (in different ways), multiple components will alias the same data and there is no obvious answer to which component owns the data.
 - Given a lack of obvious ownership, it also isn't obvious which part of the application should be responsible for synchronizing data with the backend. For this reason, pagination of search results was a serious challenge in I-analyzer.
 - In a hierarchy of components that share the same data, it seems obvious that the topmost component is the owner, but this contributes to the rise of god components like I-analyzer's former search component.
 - There is no way to detect internal changes in objects and arrays; RxJS can only represent these, and Angular components can only follow up on them, if the object or array is replaced wholesale. It is also impossible to subscribe only to changes in a specific property of an object.

I believe that as an indirect effect, (large) Angular projects are more likely to become messy. Messiness is a serious problem; messier projects take more time to develop and maintain and messiness attracts more messiness, leading to a vicious circle of messiness and wasted time.

Let's discuss whether this is an issue we want to address (I vote yes) and if so, how we might solve or at least reduce it.

Regarding a (partial) solution, I would like to kick off with a quick exploration of what it might look like if we attempt to replicate Backbone.Model-like functionality in an Angular context, respecting conventions such as the use of RxJS observables as sources of events. In the ideal case, this might lead to a reusable NPM package which is useful to us and to the Angular community at large.

The original Backbone.Model is an extensible class, of which the instances

 - own an object of interest (the payload), which can be modified in-place;
 - facilitate asynchronous CRUD operations to the server;
 - emit events when the payload changes, both per-property and for the object as a whole, providing temporary access to both the old and the new value;
 - provide utility-belt conveniences such as a mapped id attribute, validation, JSON conversion, defaults and various algorithms.

Mapping this to an Angular context, we get

> an extensible class

This, at least, is easy to do.

> of which the instances
>
>  - own an object of interest (the payload), which can be modified in-place;

For reasons we will see next, this would likely be a private property of a publicly available type. The payload may then be exposed through accessors. Example:

```ts
// Somewhere in our library
export class AngularModel<Attributes extends object = object> {
    private attributes: Attributes;
    // of course, more fields and methods which we don't show here
}

// Using it in client code
export interface UserAttributes {
    username: string;
    email?: string;
    phone?: string;
}

export class UserModel extends AngularModel<UserAttributes> {}

// Inside another module
let user = new UserModel({username: 'dhlab'});

// per-property accessors
user.email.set('dhlab@dhlab.edu');
user.email.get(); // dhlab@dhlab.edu

// global accessors
// (let's say get() returns a clone and set() changes only
// explicitly mentioned properties)
user.get(); // {username: 'dhlab', email: 'dhlab@dhlab.edu'}
user.set({phone: '34522338'});
```

Of course, the accessors don't have to be called `get` and `set`. We could opt for a get/set descriptor like `.value` instead. In the ideal case, the proxy properties and their accessors are automatically generated from a [type mapping](http://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types). If this isn't possible, we might opt for something slightly more like the Backbone original:

```ts
user.get('email');
```

This can still be typechecked by requiring arguments that name an attribute to be `keyof Attributes`.

>  - facilitate asynchronous CRUD operations to the server;

Quite obviously, `AngularModel` instances should have `.save()`, `.fetch()` and `.destroy()` methods (or similar). There should probably be a way to set the URL to the API where models of a given subclass can be synced, perhaps with a class decorator. The `.save` method *et al* may also have a `.subscribe` method so an observer can be informed of synchronization events without having to be the initiator of the request. There is a lot of choice here in how fine-grained such events should be.

>  - emit events when the payload changes, both per-property and for the object as a whole, providing temporary access to both the old and the new value;

The previously mentioned proxy properties, as well as the model instance as a whole, may offer `.subscribe()` methods for this purpose. The `onNext` handler of a proxy property might receive objects of signature `{ value: Attributes[A]; previousValue: Attributes[A]; }` where `A` is a particular `keyof Attributes`. Likewise, whole-instance `onNext` handlers might recieve `{ attributes: Attributes; previousAttributes: Attributes; }`. Events should only be emitted if the value actually changes.

Again, if proxy properties cannot be automatically generated, we may opt for a workaround like `user.track('email').subscribe()`.

Actually using such a subscription from a component is still not trivial, because Angular takes the responsibility for updating the view completely out of the hands of the developer. It might be best to alias the properties that are used in the template on the component, with the understanding that the component always only mirrors those properties rather than owning them. The component would then subscribe to the model in order to update its alias, and optionally synchronize the other way in the `ngOnChanges` method. It may require some creativity to keep boilerplate code to a minimum.

>  - provide utility-belt conveniences such as a mapped id attribute, validation, JSON conversion, defaults and various algorithms.

This is up to our imagination. JSON conversion is probably useful for the CRUD methods. Validation might not be a first priority, given that Angular has form validation, although validating a form is not the same as validating an object.

Porting Backbone.Collection to Angular would be similar, but with an array of models as its payload. This brings different CRUD operations, different change events to which one might subscribe (`add`, `remove`, `sort` etcetera) and different utility-belt methods (such as `.push` and `.pop`).

**Comment by jgonggrijp** [comment]
Mentioning @BeritJanssen and @oktaal because I just realized you aren't watching this repository.

**Comment by alexhebing** [comment]
I held off responding to this question for a few days, because frankly, I was a bit upset by it. It seems to me that a discussion like this takes the endless debate we had on A(ngular) vs B(ackbone) and attempts to reintroduce it into our working with A. I really want to avoid that, and am even tempted not respond to the content of the question, because I feel this discussion has already taken up so much time that we could have used to move forward (in whichever direction), that it simply makes me sad. On the other hand, this seems to be a way we do things at the Lab, so here goes, but I'll be brief, just a couple of questions.

- Many people work with A, how do they implement data management, i.e. solve this problem?
- Let's not introduce new, non-A solutions into our Angular applications, but go with the flow. What, for example, could be the role of Angular's `services` in this regard?
- Is there any application that we are currently building for which this is an issue? I-analyzer is the example, but I am quite sure we will not drastically change the structure of that application. Read IT is the obvious other example, but it is in B. Is this really a problem we need to solve now?

**Comment by jgonggrijp** [comment]
>  - Many people work with A, how do they implement data management, i.e. solve this problem?

I don't know. My impression is that it is an unsolved problem. Maybe @oktaal can answer this question.

>  - Let's not introduce new, non-A solutions into our Angular applications, but go with the flow.

This is exactly what I'm proposing.

>  What, for example, could be the role of Angular's services in this regard?

Angular's services are just global singleton objects. A model should be global singleton object (i.e., a service) if there exists exactly one unique instance during the lifetime of the application. In some situations, there might also be a service that produces or consumes model instances. In general, models and services are orthogonal features; they serve different purposes.

>  - Is there any application that we are currently building for which this is an issue?

I think I-analyzer has suffered from this problem. I suspect the other Angular-applications (Gretel and Moedint) might be suffering from this, too, but I don't know those codebases well enough to judge.

>  I-analyzer is the example, but I am quite sure we will not drastically change the structure of that application.

@BeritJanssen has been drastically changing the structure of I-analyzer for the past few months because of maintainability. If we want to add more features in the future, I think (gradually?) adopting models into the application will save time.

>  Read IT is the obvious other example, but it is in B.

As you say, Read-IT is not in Angular, so I don't see how it is an obvious example.

>  Is this really a problem we need to solve now?

This is the question I'm asking you; is this a problem we want to address? I'm getting the impression you'd vote "no".

Just to be clear, I said nowhere that we should solve it *now immediately, first thing*. I'm just suggesting that we will save time if we address this. Of course, as always with maintainability problems, the sooner we address the issue, the more time we'll save. There will be new Angular applications soon enough.

**Comment by alexhebing** [comment]
Some clarifications: 

1) your argument starts from the idea that in Angular, there is 'no separation of concerns between storing data and presenting data', i.e. components do both. If a service in Angular is a 'global singleton object', could you make a service responsible for storing the data and inject this service into all components, thus separating concerns?

2) Angular already contains many 'parts' (components, services, modules, pipes, etc). Isn't there one (Iwas thinking of services, see 1) that offers us a way to have what we want without building new ('non-A') parts?

3) My thinking of Read-IT as an obvious example pertains to your suggestion that `(large) Angular projects are more likely to become messy': I think that Read-IT is the only other large application currently under active development, but I might be mistaken.

**Comment by jgonggrijp** [comment]
> 1. your argument starts from the idea that in Angular, there is 'no separation of concerns between storing data and presenting data', i.e. components do both. If a service in Angular is a 'global singleton object', could you make a service responsible for storing the data and inject this service into all components, thus separating concerns?

I guess you could. It would be a different solution with different trade offs. For example, it would be challenging to ensure that temporary data used in one place don’t overwrite temporary data used in another place, but clients can still find back whatever they submitted. That is, if you don’t want to make the storage service omniscient, which I think you don’t want because that would be an extreme case of a god object. I think it would boil down to creating a specialized central key-value store. You’d then have to fiddle with unique identifiers to prevent naming conflicts.

To be honest, I don’t think it would be any more “standard Angular” than a model class. In fact, I think it would be more exotic and fiddly.

> 2. Angular already contains many 'parts' (components, services, modules, pipes, etc). Isn't there one (Iwas thinking of services, see 1) that offers us a way to have what we want without building new ('non-A') parts?

If I believed that Angular had such a part, I wouldn’t raise this issue in the first place.

> 3. My thinking of Read-IT as an obvious example pertains to your suggestion that `(large) Angular projects are more likely to become messy': I think that Read-IT is the only other large application currently under active development, but I might be mistaken.

I wrote (large) because the problem of messiness grows exponentially with the size and age of the application. I believe that having models saves time at all scales, though.

**Comment by alexhebing** [comment]
I guess what I was afraid would happen is already happening. I could ask more questions and you could give more answers, but I feel we are not moving towards a conclusion in any sense. A game of ping-pong _ohne ende_. We shouldn't.

More generally, then, and perhaps mostly addressed to @JosedeKruif, I feel our decision-making about this type of questions needs a plan, a way in which we can avoid endless discussions, and/or us sitting around doing nothing in the face of serious problems. Imagine if all six of us start arguing in this thread, how much time and money does that cost? If my first response sounded irritated this is not at all because I feel @jgonggrijp is raising irrelevant issues, but I seriously want to avoid lengthy discussions leading nowhere (fast).

**Comment by jgonggrijp** [comment]
You are right.

We can avoid lengthy discussion, and still achieve something here and now (without waiting for the next structuuroverleg), by tallying a closed-question vote:

**Do you think that the lack of models in Angular will cost us time (unless we do something about it)?**
(Available answers: yes, no, maybe.)

Julian: yes.

**Comment by oktaal** [comment]
Well... look at that: https://github.com/angular-extensions/model That's the advantage of not being the only one developing using this framework, somebody else might already have already come up with a solution. :stuck_out_tongue_winking_eye:

The proposed question here is moot as Angular _has_ models (simple example here: https://nehalist.io/working-with-models-in-angular/) they are just what you put in and get out of services. There is even an [`NgModel`](https://angular.io/api/forms/NgModel). That those models aren't like Backbone's models isn't the problem of Angular but yours.

Other than that I think these kinds of discussions can best be held when _actually implementing actual functionality_ and see how things in a concrete solution could actually be improved upon.

**Comment by jgonggrijp** [comment]
@oktaal "Has something that it calls a model" is not the same as "has models in the MVC sense". That said, the angular-extensions/model does seem to provide models in that sense, at first glance. My apologies for not having been able to find that extension myself.

> Other than that I think these kinds of discussions can best be held when *actually implementing actual functionality* and see how things in a concrete solution could actually be improved upon.

Please. I gave examples from I-analyzer, which I worked on. I didn't just fantasize this out of thin air.
