### ISSUE TITLE
Change repository to template

### ISSUE THREAD

**Issue by kequach** [CentreForDigitalHumanities/cookiecutter-webapp-deluxe#32]
Having a quick look at this repository it seems to me that this could be marked as a template. How you can do this is described here: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository
You can take a look at [SWORDS](https://github.com/UtrechtUniversity/SWORDS-UU) for example to see how this would look like. If you need help, please feel free to reach out.

**Comment by jgonggrijp** [comment]
Thanks for the suggestion, but GitHub repository templates do not cover all of our needs. We use [Cookiecutter](https://pypi.org/project/cookiecutter/), which goes beyond just providing a fixed set of files. It interpolates values inside files based on customizable parameters, generates files conditionally and enables us to run pre- and post-generation setup code.
