### ISSUE TITLE
Missing frontend package.json

### ISSUE THREAD

**Issue by lukavdplas** [CentreForDigitalHumanities/cookiecutter-webapp-deluxe#44]
To replicate, run the cookiecutter and accept all default options (including the angular frontend).

The script generates a file `frontend/package.overwrite.json` but not `frontend.package.json`.

(Because of this, running `yarn` after installation becomes recursive and never stops running.)

**Comment by lukavdplas** [comment]
Note: renaming package.overwrite.json to package.json does allow you to install dependencies, though it does not yet result in a working frontend, for reasons beyond me. I got the following error when running `yarn start` in the frontend.

<pre><font color="#AAAAAA">$ ng serve --proxy-config ../proxy.conf.json</font>
<font color="#CC0000"><b>Error: This command is not available when running the Angular CLI outside a workspace.</b></font>
</pre>

**Comment by JeltevanBoheemen** [comment]
Sounds like there were some problems along the way. I had my share of half-finished cookiecutter projects. What's in `bootstrap.log`?

**Comment by lukavdplas** [comment]
Ah, I see the problem! The bootstrap script failed because I had node 14.17. I thought I had updated node somewhere before this particular run for the cookiecutter script, but apparently it was afterwards, so the frontend was left unfinished.
