### ISSUE TITLE
update template readme

### ISSUE THREAD

**Issue by lukavdplas** [CentreForDigitalHumanities/cookiecutter-webapp-deluxe#47]
The template readme lists a lot of the technical details for developers and little else, which makes sense: other information is usually project specific. But the result is that we often end up using the existing readme as a "template" and keep the same basic structure.

A specific effect is that many of our readmes are structured like

> # cool project
> this project is an interface to do some cool humanities thing!
>
> ## before you start
>you need to install node, postgres, python, etc. etc.

where it's missing the information that this is a web application and those prerequisites are mostly for development/deployment, and that the rest of the readme is not a user manual but a development manual.

We can use this template as a basis instead: https://github.com/UtrechtUniversity/FAIR-Cheatsheets/blob/main/cheatsheets/FAIR_code_publishing/README_FAIR_code_publishing.md

Personally I would support:
- Moving some of the information in the current readme to a separate "development readme" / "development guide" etc.
- Letting the template readme contain some visibly unfinished sections like "fill in contact information here". (Our current readme looks finished after filling in a project title and tagline, but I think this makes it too tempting to leave it as-is.)

**Comment by JeltevanBoheemen** [comment]
Excellent idea, and I like the provided template.
The developer information we currently have could maybe be moved to a CONTRIBUTING.md?

**Comment by lukavdplas** [comment]
The [github documentation on contributing.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) suggests


- Steps for creating good issues or pull requests.
- Links to external documentation, mailing lists, or a code of conduct.
- Community and behavioral expectations.

So it's more a code of conduct than technical documentation.

**Comment by jgonggrijp** [comment]
In my experience, contributing.md is definitely also a "how to develop". A code of conduct is a different beast, that's why you put a link to it in the contributing.md.
