### ISSUE TITLE
hyphen in database variables

### ISSUE THREAD

**Issue by JeltevanBoheemen** [CentreForDigitalHumanities/cookiecutter-webapp-deluxe#5]
When adopting a slug with a hyphen (e.g. `prevention-matrix`), the default values for database_name and database_user are this slug. PostgreSQL does not allow hyphens here, unless the entire variable is enclosed by double quotes. In this case, all future references to the database have to be enclosed in double quotes as well. This is undesirable. 

I propose to replace any `-` by `_` in `database_name` and `database_user` variables are replaced by underscores (similar to Angular app names).

**Comment by jgonggrijp** [comment]
Slugs are not supposed to contain hyphens in general. For example, python package names must not contain hyphens, either. "Slug" is generally understood to be a word that could be the name of a variable in common programming languages.

Did the cookiecutter produce this automatically? In that case, it's a bug.

**Comment by JeltevanBoheemen** [comment]
My bad. The cookiecutter didn't produce this automatically. I just tried to follow convention of DH git repositories (most of them are `foo-bar` as opposed to `foo_bar`). I have no problem using the underscore notation. Closing this.
