### ISSUE TITLE
Breaks when generating using newer Angular CLI

### ISSUE THREAD

**Issue by oktaal** [CentreForDigitalHumanities/cookiecutter-webapp-deluxe#6]
Triggered a recompile and the generation breaks: 
https://travis-ci.org/UUDigitalHumanitieslab/cookiecutter-webapp-deluxe

It might be useful to check/enforce a certain version. See #4

**Comment by jgonggrijp** [comment]
Suggestion: install angular CLI to the local `node_modules` and use that.

**Comment by oktaal** [comment]
Maybe something like:

[`npx`](https://www.npmjs.com/package/npx)`-p @angular/cli@7 ng new $PROJECT_NAME`

Could work.

**Comment by jgonggrijp** [comment]
Yes or maybe just `yarn ng new` if you include it in the `devDependencies`.
